Repository afaneca/myfin-api, pull requests merged in 2025-02, with the labels that each got.

#107 106-replace-db_table-with-db_name-in-envexample
  .env.example
  src/config/db.config.js
Labels: documentation, enhancement

#108 2.8.1
  .env.example
  src/config/db.config.js
Labels: documentation, enhancement

#112 109-fix-post-usersdemo-constraints-error
  .editorconfig
  .idea/codeStyles/Project.xml
  package-lock.json
  package.json
  src/utils/demoDataManager.ts
Labels: bug

#113 2..8.2
  .editorconfig
  .idea/codeStyles/Project.xml
  package-lock.json
  package.json
  src/utils/demoDataManager.ts
Labels: bug

#115 114-add-release-drafter-bot
  .github/release-drafter.yml
Labels: maintenance

#111 Add container support and auto container builds for releases
  .dockerignore
  .github/workflows/build-container-api.yml
  Dockerfile
  prisma/schema.prisma
Labels: enhancement, maintenance

#118 2.8.4
  Dockerfile
  package.json
Labels: bug

#123 120-get-statsdashboardmonth-expenses-income-distribution-improve-error-handling
  src/services/statsService.ts
Labels: enhancement

#124 2.9.0
  Dockerfile
  package-lock.json
  package.json
  src/services/categoryService.ts
  src/services/statsService.ts
  src/services/transactionService.ts
Labels: bug, enhancement

#126 125-fix-get-budgets-when-there-are-no-transactions
  .github/workflows/release-drafter.yml
  src/services/accountService.ts
Labels: bug

#127 2.9.1
  .github/workflows/release-drafter.yml
  Dockerfile
  package.json
  src/services/accountService.ts
Labels: bug

#129 Fix sql query in getAmountForCategoryInPeriod #128
  src/services/categoryService.ts
  src/utils/demoDataManager.ts
Labels: bug

#133 Docker: Support multi-arch builds #132
  .github/workflows/build-container-api.yml
Labels: maintenance

#100 99-add-first-integration-tests
  .env.test
  .github/workflows/integrationTests.yml
  Dockerfile
  __tests__/integration/account.integration.test.ts
  __tests__/integration/transaction.integration.test.ts
  __tests__/integration/user.integration.test.ts
  __tests__/integration/utils/resetDb.ts
  __tests__/integration/utils/setup.ts
  __tests__/integration/utils/testUtils.ts
  __tests__/unit/budgetService.test.ts
  __tests__/unit/prisma.mock.ts
  __tests__/unit/tagService.test.ts
  docker-compose.tests.yml
  package.json
  src/services/transactionService.ts
  src/utils/DateTimeUtils.js
  vitest.config.integration.ts
  vitest.config.unit.ts
Labels: maintenance
